import Me from './Me.jpg';
import Insta from './insta.png';
import close from './close.svg';
import menu from './menu.svg';
import epk from './epk.png';
import dollarsign from './dollar-sign.png';
import home from './home.png';
import alert from './alert-circle.png';
import us from './us.png';
import rfs1 from './rfs1.png';
export { Me, Insta, close, menu, epk, dollarsign, home, alert, us, rfs1 };
